[theme]
primaryColor = "#FFFFFF"  # Couleur principale, à adapter selon vos préférences
backgroundColor = "#000000"  # Couleur de fond, à adapter
secondaryBackgroundColor = "#000000"  # Couleur secondaire
textColor = "#FFFFFF"  # Couleur du texte

[browser]
gatherUsageStats = false

[ui]
favicon = "images/rag-eau.png"
