[theme]
primaryColor = "#000000"  # Couleur principale, à adapter selon vos préférences
backgroundColor = "#FFFFFF"  # Couleur de fond, à adapter
secondaryBackgroundColor = "#FFFFFF"  # Couleur secondaire
textColor = "#000000"  # Couleur du texte

[browser]
gatherUsageStats = false

[ui]
favicon = "images/rag-eau.png"
