MISTRAL_API_KEY = "bp0TJUn9HbsKU7amQ2PvlBN4DzWkIqLH"
OPENAI_API_KEY = "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"
